-- v1.9: Messenger-style reactions for chat messages.

create table if not exists public.message_reactions (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families (id) on delete cascade,
  room_id uuid not null references public.rooms (id) on delete cascade,
  message_id bigint not null references public.messages (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  reaction text not null check (length(trim(reaction)) > 0 and length(reaction) <= 8),
  created_at timestamptz not null default timezone('utc', now()),
  unique (message_id, user_id)
);

create index if not exists idx_message_reactions_room_message
on public.message_reactions (room_id, message_id);

create index if not exists idx_message_reactions_message
on public.message_reactions (message_id);

create or replace function app.assert_message_reaction_room_family_match()
returns trigger
language plpgsql
as $$
declare
  v_message public.messages%rowtype;
begin
  select m.*
  into v_message
  from public.messages m
  where m.id = new.message_id;

  if not found then
    raise exception 'message % does not exist', new.message_id
      using errcode = '23503';
  end if;

  if new.family_id <> v_message.family_id then
    raise exception 'family_id mismatch for message %', new.message_id
      using errcode = '23514';
  end if;

  if new.room_id <> v_message.room_id then
    raise exception 'room_id mismatch for message %', new.message_id
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_message_reactions_room_family_check on public.message_reactions;
create trigger trg_message_reactions_room_family_check
before insert or update on public.message_reactions
for each row execute function app.assert_message_reaction_room_family_match();

alter table public.message_reactions enable row level security;

create policy message_reactions_select_same_family
on public.message_reactions
for select
using (app.is_family_member(family_id));

create policy message_reactions_insert_self
on public.message_reactions
for insert
with check (
  app.is_family_member(family_id)
  and user_id = auth.uid()
);

create policy message_reactions_update_self
on public.message_reactions
for update
using (
  app.is_family_member(family_id)
  and user_id = auth.uid()
)
with check (
  app.is_family_member(family_id)
  and user_id = auth.uid()
);

create policy message_reactions_delete_self
on public.message_reactions
for delete
using (
  app.is_family_member(family_id)
  and user_id = auth.uid()
);

