-- Initial v1 scaffold schema for Family Hub.
-- Focus: planning-level tables + RLS intent stubs.

create extension if not exists pgcrypto;

create schema if not exists app;

create type public.family_role as enum ('owner', 'admin', 'member');
create type public.invite_status as enum ('pending', 'accepted', 'revoked', 'expired');
create type public.room_type as enum ('chat', 'game');
create type public.game_status as enum ('pending', 'active', 'finished', 'cancelled');

create table public.families (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_by uuid not null references auth.users (id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.family_members (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.family_role not null default 'member',
  status text not null default 'active' check (status in ('active', 'left', 'removed')),
  joined_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  unique (family_id, user_id)
);

create table public.invites (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  invited_by uuid not null references auth.users (id),
  invitee_contact text,
  token text not null unique,
  status public.invite_status not null default 'pending',
  expires_at timestamptz not null,
  accepted_by uuid references auth.users (id),
  accepted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  kind public.room_type not null,
  slug text not null,
  title text not null,
  created_by uuid not null references auth.users (id),
  created_at timestamptz not null default timezone('utc', now()),
  unique (family_id, slug)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families (id) on delete cascade,
  room_id uuid not null references public.rooms (id) on delete cascade,
  sender_id uuid not null references auth.users (id),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.games (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  room_id uuid not null references public.rooms (id) on delete cascade,
  created_by uuid not null references auth.users (id),
  mapping_id text not null default 'classic_v1',
  status public.game_status not null default 'pending',
  current_turn_user_id uuid references auth.users (id),
  winner_user_id uuid references auth.users (id),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.game_players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games (id) on delete cascade,
  family_id uuid not null references public.families (id) on delete cascade,
  user_id uuid not null references auth.users (id),
  player_order int not null check (player_order > 0),
  tile_position int not null default 1 check (tile_position between 1 and 100),
  token_avatar_pack_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  unique (game_id, user_id),
  unique (game_id, player_order)
);

create table public.game_events (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games (id) on delete cascade,
  family_id uuid not null references public.families (id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  family_id uuid not null references public.families (id) on delete cascade,
  display_name text,
  avatar_style_id text,
  cinematics_enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.avatar_packs (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  style_id text not null,
  version int not null check (version > 0),
  status text not null default 'ready' check (status in ('queued', 'processing', 'ready', 'failed')),
  base_path text not null,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default timezone('utc', now()),
  unique (family_id, user_id, style_id, version)
);

alter table public.game_players
  add constraint game_players_token_avatar_pack_id_fkey
  foreign key (token_avatar_pack_id) references public.avatar_packs (id) on delete set null;

create index if not exists idx_family_members_user_id on public.family_members (user_id);
create index if not exists idx_invites_family_id on public.invites (family_id);
create index if not exists idx_rooms_family_id on public.rooms (family_id);
create index if not exists idx_messages_room_created on public.messages (room_id, created_at desc);
create index if not exists idx_games_family_status on public.games (family_id, status);
create index if not exists idx_game_players_game_id on public.game_players (game_id);
create index if not exists idx_game_events_game_created on public.game_events (game_id, created_at desc);
create index if not exists idx_user_profiles_family_id on public.user_profiles (family_id);
create index if not exists idx_avatar_packs_family_user on public.avatar_packs (family_id, user_id);

create or replace function app.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create trigger trg_families_touch_updated_at
before update on public.families
for each row execute function app.touch_updated_at();

create trigger trg_games_touch_updated_at
before update on public.games
for each row execute function app.touch_updated_at();

create trigger trg_user_profiles_touch_updated_at
before update on public.user_profiles
for each row execute function app.touch_updated_at();

create or replace function app.is_family_member(target_family_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.family_members fm
    where fm.family_id = target_family_id
      and fm.user_id = auth.uid()
      and fm.status = 'active'
  );
$$;

create or replace function app.family_role_for_user(target_family_id uuid)
returns public.family_role
language sql
stable
as $$
  select fm.role
  from public.family_members fm
  where fm.family_id = target_family_id
    and fm.user_id = auth.uid()
    and fm.status = 'active'
  limit 1;
$$;

alter table public.families enable row level security;
alter table public.family_members enable row level security;
alter table public.invites enable row level security;
alter table public.rooms enable row level security;
alter table public.messages enable row level security;
alter table public.games enable row level security;
alter table public.game_players enable row level security;
alter table public.game_events enable row level security;
alter table public.user_profiles enable row level security;
alter table public.avatar_packs enable row level security;

create policy families_select_family_members
on public.families
for select
using (app.is_family_member(id));

create policy families_insert_creator
on public.families
for insert
with check (auth.uid() = created_by);

create policy families_update_owner_admin
on public.families
for update
using (app.family_role_for_user(id) in ('owner', 'admin'))
with check (app.family_role_for_user(id) in ('owner', 'admin'));

create policy family_members_select_same_family
on public.family_members
for select
using (app.is_family_member(family_id));

create policy family_members_insert_owner_admin
on public.family_members
for insert
with check (app.family_role_for_user(family_id) in ('owner', 'admin'));

create policy family_members_update_owner_admin
on public.family_members
for update
using (app.family_role_for_user(family_id) in ('owner', 'admin'))
with check (app.family_role_for_user(family_id) in ('owner', 'admin'));

create policy family_members_delete_owner_admin
on public.family_members
for delete
using (app.family_role_for_user(family_id) in ('owner', 'admin'));

create policy invites_select_same_family
on public.invites
for select
using (app.is_family_member(family_id));

create policy invites_manage_owner_admin
on public.invites
for all
using (app.family_role_for_user(family_id) in ('owner', 'admin'))
with check (app.family_role_for_user(family_id) in ('owner', 'admin'));

create policy rooms_select_same_family
on public.rooms
for select
using (app.is_family_member(family_id));

create policy rooms_manage_owner_admin
on public.rooms
for all
using (app.family_role_for_user(family_id) in ('owner', 'admin'))
with check (app.family_role_for_user(family_id) in ('owner', 'admin'));

create policy messages_select_same_family
on public.messages
for select
using (app.is_family_member(family_id));

create policy messages_insert_member
on public.messages
for insert
with check (
  app.is_family_member(family_id)
  and sender_id = auth.uid()
);

create policy games_select_same_family
on public.games
for select
using (app.is_family_member(family_id));

create policy games_write_service_role
on public.games
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy game_players_select_same_family
on public.game_players
for select
using (app.is_family_member(family_id));

create policy game_players_write_service_role
on public.game_players
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy game_events_select_same_family
on public.game_events
for select
using (app.is_family_member(family_id));

create policy game_events_insert_service_role
on public.game_events
for insert
with check (auth.role() = 'service_role');

create policy user_profiles_select_same_family
on public.user_profiles
for select
using (app.is_family_member(family_id));

create policy user_profiles_insert_self
on public.user_profiles
for insert
with check (
  app.is_family_member(family_id)
  and user_id = auth.uid()
);

create policy user_profiles_update_self
on public.user_profiles
for update
using (
  app.is_family_member(family_id)
  and user_id = auth.uid()
)
with check (
  app.is_family_member(family_id)
  and user_id = auth.uid()
);

create policy avatar_packs_select_same_family
on public.avatar_packs
for select
using (app.is_family_member(family_id));

create policy avatar_packs_write_service_role
on public.avatar_packs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
